### ISSUE TITLE
PDF converter package.

### ISSUE THREAD

**Issue by vamsi1306** [vamsi1306/LargePdf-console#1]
Decide on a PDF converter Package and post why have you decided on it.

**Comment by vamsi1306** [comment]
References: [https://blog.aspose.com/2020/07/26/images-to-pdf-csharp/](AsposePdf)

**Comment by DeepakAvula** [comment]
https://stackoverflow.com/a/28670147 - states it is tough to create a converter, so that idea should be dropped.

**Comment by DeepakAvula** [comment]
https://www.youtube.com/watch?v=GqEH8XvPZwM - gives a clear description of PDF.

**Comment by vamsi-alluri** [comment]
Tried it with Aspose worked well. PDF sharp doesn't work yet for image conversions. But, for PDF merging PDF sharp works better than Aspose.

Considering this issue as closed.
